# Generated by Django 5.2.17 on 2026-08-17 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CARD', 'Tarjeta'), ('BANK_ACCOUNT', 'Cuenta bancaria'), ('CLABE', 'CLABE'), ('OTHER', 'Otro')], max_length=20)),
                ('alias', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('identifier_hash', models.CharField(max_length=128)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='payment_met_user_id_15ff19_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'identifier_hash'), name='unique_user_payment_identifier')],
            },
        ),
    ]
