# Generated by Django 5.2.17 on 2026-08-18 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentmethod',
            new_name='payment_met_user_id_cad3f0_idx',
            old_name='payment_met_user_id_15ff19_idx',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='payment_methods',
        ),
    ]
