# Generated by Django 5.2.17 on 2026-08-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('REGISTER', 'Register'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE_PAYMENT_METHOD', 'Create payment method'), ('VIEW_PAYMENT_METHOD', 'View payment method'), ('DELETE_PAYMENT_METHOD', 'Delete payment method'), ('REACTIVATE_PAYMENT_METHOD', 'Reactivate payment method')], max_length=50),
        ),
    ]
